### ISSUE TITLE
Refactor of the resource.Lookup to be part of the query package

### ISSUE THREAD

**Issue by rs** [rs/rest-layer#112]
The more I think of the current `resource.Lookup` type and how it interacts with the resource, the more I think there is room for improvement and simplification.

I would see the current `query.Query` become just the `Predicate` field of a new `query.Query` type that would also contain the selection (properly renamed projection), the sort and the window (offset, limit). This new type would follow the current `Query` behavior of having a parsing phase dissociated from the validation phase.

This new `Query` type type would be usable on `resource` and would abstract most of the boiler plate code that is in both `rest` and `graphql` packages to create and validate a `Lookup`. By simplifying the `resource` API we also make it more usable without the `rest` or `graphql` package if one is only interested by the "ORM" part of rest-layer. The `schema`/`query` packages would also usable without the `resource` package if wanted without having to re-implement the projection logic.

Here is the definition of those new types:

```go
package query

type Query struct {
	// Projection is the list of fields from the items of the result that should
	// be included in the query response. A projected field can be aliased or
	// given parameters to be passed to per field transformation filters. A
	// projection is hierachical allow projection of deep structures.
	//
	// A DSL can be used to build the projection structure.
	Projection []Projection

	// Predicate defines the criteria an item must meet in order to be
	// considered for inclusion in the result set.
	//
	// A DLS can be used to build a predicate from a MongoDB like expressions.
	Predicate Predicate

	// Sort is a list of fields or sub-fields to use for sorting the result set.
	Sort Sort

	// Window defines result set windowing using an offset and a limit. When
	// nil, the full result-set should be returned.
	Window *Window
}

// New creates a query from a projection, predicate and sort queries using
// their respective DSL notations. An optional window can be provided.
//
// Example:
//
//   New("foo{bar},baz:b", `{baz: "bar"}`, "foo.bar,-baz", Page(1, 10, 0))
//
// Select items with the foo field equal to bar, including only the foo.bar and
// baz fields in the result set, with the baz field aliased to b. The result is
// then sorted by the foo.bar field asending and baz descending. The result is
// windowed on page 1 with 10 items per page, skiping no result.
func New(projection, predicate, sort string, window *Window) (Query, error) {}

// Validate validates the query against the provided validator.
func (Query) Validate(validator schema.Validator) error {}

type Projection struct {
	// Name is the name of the field as define in the resource's schema.
	Name string

	// Alias is the wanted name in the representation.
	Alias string
	
	// Params defines a list of params to be sent to the field's param handler
	// if any.
	Params map[string]interface{}
	
	// Children holds references to child projections if any.
	Children []Projection
}

// ReferenceResolver is a function resolving a reference to another field.
type ReferenceResolver func(path string) (*Resource, error)

// ParseProjection creates a Projection from its DSL representation.
func ParseProjection(projection string) (Projection, error) {}

// Validate validates the projection against the provided validator.
func (Projection) Validate(validator schema.Validator) error {}

// Apply applies the projection on the given payload with the help of the
// validator. The resolver is used to fetch payload of references outside of the
// current payload.
func (Projection) Apply(ctx context.Context, payload map[string]interface{}, validator schema.Validator, resolver ReferenceResolver) (map[string]interface{}, error) {}

// String output the projection in its DSL form.
func (Projection) String() string {}

type Predicate []Expression // see query.Expression

// ParsePredicate parses a predicate expression in its DSL format.
func ParsePredicate(expression string) (Predicate, error) {}

// MustParsePredicate parses a predicate expression in its DSL format and panic
// on error.
func MustParsePredicate(expression string) Predicate {}

// Match returns true if the payload matches the predicate.
func (Predicate) Match(payload map[string]interface{}) bool {}

// Validate validates the predicate againast the provided validator.
func (Predicate) Validate(validator schema.Validator) error {}

// String outputs the predicate as string using the DSL.
func (Predicate) String() string {}

type Sort []SortField

type SortField struct {
	// Name is the name of the field to sort on.
	Name string

	// Reversed instruct to reverse the sorting if set to true.
	Reversed bool
}

// ParseSort parses a sort expression. A sort expression is a list of fields
// separated by comas. A field sort is reverse if preceded by a minus sign (-).
func ParseSort(sort string) (Sort, error) {}

// Validate validates the sort againast the provided validator.
func (Sort) Validate(validator schema.Validator) error {}

type Window struct {
	// Offset is the 0 based index of the item in the result set to start the
	// window at.
	Offset int

	// Limit is the maximum number of items to return in the result set.
	Limit int
}

// Page creates a Window using pagination.
func Page(page, perPage, skip int) {}
```

Is would be another major refactor and would again break the compatibility with storers but it's better now than later right? :)

Thoughts @smyrman?

**Comment by smyrman** [comment]
I had to read up on the `resource.Lookup` code a bit, but I think this proposed change makes sense:
- It's all "query" related, so to have a single type for all of this, and to have it in the `query` package, all makes sense.
- I sort of like that members of the Query struct are made public. It was never completely clear to me if the current `resource.Lookup` allowed for Storers to optimize projection by fetching only the necessary fields, but with this change it looks pretty feasible to do so.

I also have one constructive comment to the proposed code. I have really just read one book on Clean Code, and that is [the one](https://www.amazon.com/Clean-Code-Handbook-Software-Craftsmanship/dp/0132350882) by Robert. C. Martin. It's an old book, but pretty good. One of his advice, would be to leave as few positional parameters as possible to a function. A function, in his opinion should have only 1 [positional] parameter, maybe 2 if there is no way to avoid it, or in extreme cases 3. This makes a lot of sense, because positional parameters are very hard to "read" when you just look at the code, and it becomes hard to write without looking up the function definition because it's easy to forget which order the parameters are supposed to be offered in.

Overall, this change would _help_ with reducing positional functional parameters, but the proposed creator functions (`New`and `Page`) in your proposed code has a lot of positional parameters, and are thus not very easy to read, and easy to use wrong if you mess up the order of the positional parameters.

clean code is also about balancing trade-offs though. I think the `Page` function is an OK convenience function with it's three parameters, but the `query.New` I would like to see with a bit fewer parameters. Since it's Go, you could also have multiple creator functions if it's needed. One reasonable initializer, would be one that parsed URL params:

```go
func Parse(query url.Values) (*Query, error) {...}
```

**Comment by smyrman** [comment]
> Is would be another major refactor and would again break the compatibility with storers but it's better now than later right? :)

I think since we are in a row of making breaking changes, it's probably better that we just go ahed and then tag a new release v0.2.0 (both for rest-layer and storers) some time _after_ we think we are done, and we had had time to uncover some bugs.

I think if/when we start using rest-layer at my company, we would push harder to get some releases out for the code versions we intend to use - at least if it's in production.

**Comment by rs** [comment]
Sure.
