### ISSUE TITLE
Content-type

### ISSUE THREAD

**Issue by laahs** [rs/rest-layer#15]
Congratulations for this beautiful initiative. Plenty of potential, very opinionated but I personally really like the "schema" and "fields" choices, it seems to fit a very large scope and be easily extended to the developer's needs. 

However, after just playing a few minutes in order to evaluate if this would really ease recoding of my website from php to go, I just tried the "users/posts" example and found that it does not seem to work with 'content-type:application/x-www-form-urlencoded' ... is this because of some settings I am not aware of yet, or did you choose to force the rest api to only be accessible through 'application/json' requests ?

Suggestion: you created useful "schema.Time", "schema.String" for instance, why not "schema.Email" and "schema.PhoneNumber" ?

By the way, this is not a real issue but I didn't know how to contact you otherwise. Does rest-layer "framework" play well with google appengine datastore and go-kit?

Is there a way to customize error messages sent for invalid data? (in order to handle multi language error dictionary for instance that generates the error message depending on language/country and error code/source of error)

**Comment by laahs** [comment]
By the way, this is not a real issue but I didn't know how to contact you otherwise. Does rest-layer "framework" play well with google appengine datastore and go-kit?

**Comment by rs** [comment]
Hi laahs, thanks for the kind words. I chose to only support JSON because urlencoded isn't typed nor structured so it would only let you support a very basic schema. If partial schema support is fine with you, a solution would be to create a middleware that would transform urlencoded POSTed data into JSON. I may provide that as an extension so it doesn't add complexity to the core framework.

About `schema.Email` and `schema.PhoneNumber`, I will certainly add them yes. Feel free to submit PR with new generic validators.

For appengine datastore, you just need to create a `resource.Storer` for it. If you do that, tell me so I can ref your handler in the documentation. I think it would be a great addition.

About go-kit, I'm not sure what you mean. If you want to have two distinct HTTP endpoints served by go-kit and rest-layer, there is no problem, they are two isolated `http.Handler`.

For error message you may try something with a custom response formater: http://rest-layer.io/#custom-response-formatter-sender. I'm planning on adding standardized error codes for each error so it would be easier to handle errors in general.

**Comment by laahs** [comment]
Hi Olivier (are you French by the way?),

thank you for your answer. Ok so this seems like your project is quite adaptable and I could overpass the obstacles that I found from first attempt of using it.

I did not have much time to go through the whole codebase for this framework, so last night I just tried to draw the big lines and concepts of how I would have seen things. After reading your comment and a little bite of the documentation you provide on http://rest-layer.io/ 

May I suggest you, though to take a look at this very basic draft I commited yesterday so that we can see where our approaches gather or differ.
https://github.com/laahs/apify

# About limitation to json content for request body and content-type:application/x-www-form-urlencoded:
As defined in the specification for web forms and **content-type:application/x-www-form-urlencoded** ( [](https://www.w3.org/TR/html401/interact/forms.html )),
"**https://maps.googleapis.com/maps/api/geocode/json?address=1600+Amphitheatre+Parkway,+Mountain+View,+CA**" is valid urlencoded data.

I think that it is easy to parse this data to a **map[string]interface{}** . name it **mapInput**. Then from a json/xml/form content, the api could generate the same map.

# Improvement suggestions:
 A **Resource** could be made of the **schema** definition and the actual **model**, which is the entity (a custom struct) stored in the **Storage** by the **Storer**. The model struct should be defined by the user. 
It needs to implement the interface Modeler
**type Modeler interface{ 
    GetStore() *Storer
}. **
Using [](https://github.com/fatih/structs) package, it is easy to retrieve a map[string]interface{} from a struct definition (name it mapDef). This map should then be used for comparison with submitted data --> in order to check data-type compatibility. It could be a simple one-to-one check, checking if each key of mapInput exists in mapDef, and if types match.

### Let's imagine that your Schema is empowered with some additional features:
Each Field could have a converter implementing the 
               Convertor interface{
                   Convert(input interface{}, *valueWithExpectedType interface{}) bool // this would check if types match, or try to convert the data from input, return false if failed
                }
          then for each field, while comparing mapInput to mapDef, the converted could be call on mapInput values. 

This would enable the "framework" to handle json/xml requests as well as basic form submit and content-type:application/x-www-form-urlencoded .

# Bigger picture:
The framework could be composed of:
- a **responder** (wrapper) that is responsible for formatting the data, with a standardize format from the data to be sent, the http error status code, and a map[source_of_issue]issue.
- **Models**
- **actors** that chain and pass data one to another, manipulating the request data and model/Item
- an **api engine** that automatically know how to generate a handler for a request with a specific method on a specific resource. It would for example read the all the Models, analyze dependencies from a Model to a ParentModel (base on the Schema.Parent information), from which it should know that a post resource should be accessed by a request to /users/:id/posts/:id2 . From the description in each resource, each schema and each field + the methods you allow on each resource, the api engine should also automatically generate api documentation.

This is what I briefly exposed in the description here **https://github.com/laahs/apify/**

**Comment by rs** [comment]
Thank you for sharing your thoughts. Let me try to answer as best as I can.

About the handling `application/x-www-form-urlencoded`, I don't really see the benefit. Maybe you have a use-case in mind that would help me understand the need?

For the `Resource` being made out of a `Schema`, I don't really understand what you mean. Today a `Resource` is the interface between a `Schema` and a `Storer`, so if I understand your suggestion, that's already how it is done.

About model being a struct, if I understand correctly, you want the storer to manage structs instead of maps right? That was the very first design of REST Layer and I quickly abandoned that idea, as it quickly became a `reflect` nightmare and it renders a lot of things more difficult with no real benefits. And all the storers I wrote until now were better at storing maps than structs. If you really need a struct at storer level, it's easy to unmarshal a map into a struct in you storer.

About the `Convertor` interface, I'm not sure it should be done at this level. The un/serialization isn't performed at `resource` or `schema` level, but in the upper `rest` or `graphql` packages. I may add more kinds of handlers like `gRPC` for instance to access the same resources from different protocols/serializations. So adding `XML` support for instance should be done in the `rest` package, but again, I don't see the benefit of supporting anything other than `JSON`. I can't recall the last time I had to build or use an API not using `JSON`.

The `responder` is the `rest.ResponseFormatter` and the `rest.ResponseSender`. It is very specific to REST as other protocols/serializations will have very specific way to handle the response.

Models are defined by schema and stored by storer. I really think it makes everything very simple as you can easily change the storage handler for a given schema without changing anything else.

The actors you describe are the resources. A `Resource` is the interface between the "representation protocol" (REST, GraphQL, gRPC…), the resource's schema and the data storage handler.

What you call the API engine is partially handled by the `resource.Index` and the `rest` package internal router. As the name of the project doesn't imply it, REST Layer isn't just about REST. For GraphQL for instance, a `/users/:id/posts/:id2` path doesn't mean anything, that's why the router is in the `rest` package and `resource` does only provide tools to interact with the hierarchical resources and their schema.

About generating documentation, it is very easy with the resource schemas and this is in the roadmap. There is already automated documentation generation provided by GraphQL support. The `rest` package will soon provide a way to expose a meta API for documentation. I may use swagger for that. Documentation is very specific to each "representation protocol" so it's not something that can be provided at the "api engine" level (`resource` or `schema` in rest-layer's topology).

I hope that may responses make sens to you. Tell me something is unclear or if I misunderstood you suggestions.

**Comment by laahs** [comment]
Hi,  

Very descriptive answer :) thank you.

## Convertor
I thought of the Convertor as a min to convert any value's type to the expected type. For example if you expect an int32, take the int64 or even string from the request body content and convert it or return false if it could not be updated. For a json only api this may be less useful because we basically only deal with key/value pairs where values can be strings, int64s or arrays of key/value pairs.

## Why not a json only API?
In my opinion, making the api able to deserialize json/xml/form values makes it very adaptive. Then, if we imagine a website with a search engine (such as an ecommerce), the user could fill a form and the data from the form would be sent directly to the api handling results without converting it to json. The iOs app would talk to the same api ... 

## Resource
Considering that I thought of models/resources as structs, I wanted to generate the struct from the map wich could be extracted from the schema. schema would be the list of constraints and validation performers, resource would be the real object stored in the storer, as is.

I understand your choice of the model being a map, and it probably is a better solution.

**Comment by lordnynex** [comment]
Hello, 

I hope you don't mind me interjecting on this issue. I wanted to avoid cluttering your issue tracker. 

Regarding non application/json content-type's (specifically `application/x-www-form-urlencoded`). I see benefit to supporting this content type for file uploads. Some examples provided by rest-layer make reference to [thumbnail images](https://github.com/rs/rest-layer/blob/master/examples/selectors/main.go#L64). This seems to create a sort of fragmentation between resources and sub resources that do not fit within the spirit of rest-layer resources. For example, I would like to implement a user schema and separate resources for multiple user photos. The photos functionality would benefit greatly from sorting and other filtering functionality already provided. As a side note `multipart/form-data` would also be beneficial and arguably more suitable for the situation I've described. Unfortunately, in many cases, it's desirable to fall back to `application/x-www-form-urlencoded` to overcome reverse proxy limitations or performance issues. For example, placing a handler like this behind nginx can have complications on older versions of nginx or installations where nginx on disk request buffering (`X-File`) is undesirable. 

I am, of course, forming these opinions without a detailed knowledge of your framework. I am about to experiment with it myself so this concern may be pointless. 

Other peripheral issues or open questions I have after reading the documentation a few times. 

I was very glad to find https://github.com/rs/rest-layer/blob/master/examples/auth/main.go because this is a critical part of the API's I work on. Is this approach aligned with your auth plans for the future? Is this approach appropriate for implementing session functionality (Basic auth is undesirable to me). If session state is stored external (not a cookie) to the request, is it logical to populate the context object with session state vars? 

One argument for supporting a more traditional 'model' interface is to provide a more intuitive place for performing RBAC or more fine grained ACL's. This may be a misguided idea. 

Lastly, I see in the example above you're using http.Error to respond to login failures. If I understand correctly, this generates a plain text error message to the client. Is that correct? In my experience, this is dangerous in mobile development if the consuming application is unprepared for plain text error messages during response deserialization. What would be the proper way to implement an error handler that adheres to the API's encoding? I am accustomed to using unrolled/render so this is a bit confusing for me currently. 

Thank you for all your hard work. I've grown to really enjoy golang but have struggled with the communities dislike of frameworks. You've clearly invested a lot of thought into rest-layer and I can proudly say that I don't mind an opinionated framework as long as it's opinions are good. I look forward to using your framework in the future.

**Comment by lordnynex** [comment]
BTW, supporting `application/x-www-form-urlencoded` for the sole purpose of supporting HTML forms is not a great argument. There are many note worthy client side frameworks (IE angular) that intercept form submit. The server side framework should not be overly concerned with making itself support all possible client access patterns. 

If there is a mechanism of implementing file uploads in a more 'RESTful' way, I'd gladly explore it.

**Comment by rs** [comment]
For now REST layer is about storing metadata, not data itself. I'm not sure it is a good idea to manipulate blobs of data via such REST APIs. In my field, we manipulate videos objects which can weigh up to several GBs. With such big objects, we need to expose a [resumable upload API](http://www.grid.net.ru/nginx/resumable_uploads.en.html) that is out of the scope of a REST API. The upload API returns a file URL (or an id) that can then be used as a reference in a REST API.

*For scaling it is better to have such blob data API separated from the metadata API as you generally don't scale them identically.*

In the doc of REST layer I'm referring to a separate "thumbnail resizer API" like [cloudinary](http://cloudinary.com). Using [field parameters](http://rest-layer.io/#field-parameters), it is easy to mask such API from the end user so he doesn't have to learn two APIs.

**Comment by rs** [comment]
About your authentication question, I think authentication is out of scope of a REST API, only authorization is. For authentication, it is best to use a separate oAuth server (or handler) and just having to manipulate [JWT](https://jwt.io) tokens from your API standpoint.

In the same idea as exposed in the [auth example](https://github.com/rs/rest-layer/blob/master/examples/auth/main.go), you can have a middleware that verify and extract user ids from the JWT token and store it in the context. You can then use [resource hooks](http://rest-layer.io/#hooks) to restrict the scope of the data the user can manipulate by injecting filter into the find lookup or ensure modified objects are owned by the authen user.

I will add an exemple with JWT if you want.

**Comment by rs** [comment]
Just added a JWT auth example: https://github.com/rs/rest-layer/blob/master/examples/auth-jwt/main.go

**Comment by lordnynex** [comment]
@rs this is extremely useful to me. Thank you very much for providing it.

**Comment by smyrman** [comment]
First thing first, I think rest-layer.io is without a doubt the best effort of creating a REST API Framework in Go yet!

Talking about support for multiple Content-Type and performance, I think if you could register your own types implementing an Encoder and/or Decoder interface either on the resource or on the index, that would be really useful. Which Encoder / Decoder gets used should check the normal Accept / Content-Type headers and do the usual "negotiation" dance.

If this interfaces got direct access to the map, then perhaps end-users could implement something like gob, flatbuffers or protobuff for improved performance both server and client side, or even do form urlencode, as asked for above?

**Comment by yanfali** [comment]
Not trying to hijack, but my 2c. schema is awesome for describing in code, validation rules for incoming parameters. I completely understand the focus on JSON as this is the best defined and easily validatable format.

As suggested by @rs I have created my own binding library to allow me to use `schema` and process incoming Form and URL parameters. If there is interest I would be happy to clean it up and contribute it to upstream or create a utility library to use with Schema. Right now I only use it for simple use cases - strings, numbers and bools. It vastly simplifies my validation code by leveraging `schema`; thank you Olivier for open sourcing this library.

**Comment by rs** [comment]
It think we can close this issue. If you feel we did not address the question, please reopen.
