### ISSUE TITLE
Storer Interface time.Now() for Created and Updated fields return unsupported time formats

### ISSUE THREAD

**Issue by SAFAD** [rs/rest-layer#180]
# Introduction: 
Using the REST Layer to build a large scale API for commercial product, we have reached a point to build our own Storer interface for PostgreSQL, heavily inspired by the SQLite and MongoDB implementations we have been able to succesfuly produce the following storage "add-on" (for PostgreSQL, but it can be easily ported to any SQL-based database) and are happily to opensource it for the community:
https://github.com/SAFAD/rest-layer-pgsql

## Issue : 
We have faced an issue with the Storer interface where using the pointer to resource.Item struct to pull the created/updated fields we receive _wrong_ time.Time format as following:
`2018-02-27 23:07:44.4179416 +0100 CET m=+7.679574500`
where ` m=+7.679574500` is additional string that is appearing from nowhere, and causing the entire API to panic when trying to format it/use it in database queries

## Reproduction:
Use the storage handler mentioned above, and add a logger or simply print the resource.Item data

## Results:
Mis-formatted time.Time data

## Expected results:
Correct time.Time data that is able to be parsed and formatted with time.Parse/time.Format

## Conclusion:
We have been able to workaround this bug for now using a _hack_ but it is not good for code quality or maintainability.

We would also love to hear your input on the library provided above and if anything missing or needs to be fixed.

### Best Regards

**Comment by smyrman** [comment]
> where m=+7.679574500 is additional string that is appearing from nowhere, and causing the entire API to panic when trying to format it/use it in database queries

It's not appearing from nowhere, it's to Go monotonic time component added in Go 1.9 https://golang.org/doc/go1.9#monotonic-time.

It can be stripped away by calling [Truncate(0)](https://golang.org/pkg/time/#Time.Truncate) on the time object before serializing it and/or by setting intial values to `time.Now().Truncate(0)` instead of `time.Now()`.

I suppose in rest-layer we should update `schema.Now` to call `Truncate(0)`:

https://github.com/rs/rest-layer/blob/a468556f73fd817100bf3b2a2d07dcf4ee19d1df/schema/time.go#L13

**Comment by smyrman** [comment]
> https://github.com/rs/rest-layer/blob/a468556f73fd817100bf3b2a2d07dcf4ee19d1df/schema/time.go#L13

Awesome 😃

**Comment by SAFAD** [comment]
I have tracked down the issue till time.Now() in time.go schema and went on to even go around golang's time source but haven't checked down to monotonic feature as of go 1.9 (which I use by default now).

I guess this can be filed as a "bug" ?

Also, I will create a new Issue suggesting using unixtime as default time field in REST Layer, it is easier to manipulate both server and client side and is more carefully standardized than other time formats.

**Comment by smyrman** [comment]
> Also, I will create a new Issue suggesting using unixtime as default time field in REST Layer, it is easier to manipulate both server and client side and is more carefully standardized than other time formats.

I am not quite sure I understand what you mean by that in this context. Most used in C and Go are probably int64 seconds since the epoch(limited precision), and int64 nanoseconds (limited range) since the epoch. In many databases, e.g. PostgreSQL TIMESTAMP, time stamps are typically stored in microseconds since the epoch, which again give different range and precision properties. The most popular JavaScript libraries use millisecond precision (to the best of my limited knowledge).

I believe the best thing rest-later can do by default is to use the built-in Go time.Time struct together with the well defined test formats it defines. This also makes it easy for a storage backend to tell a time fields apparat from a an integer.

It could be I don’t fully understand what you ask for.

**Comment by rs** [comment]
I don’t think REST layer should truncate the time. What if other storers want to use this to mesure timing for instance?

**Comment by SAFAD** [comment]
@smyrman see this: https://play.golang.org/p/kiijB0T3agv it is not unix timestamp by default in golang, its formatted.
@rs Definitely shouldn't truncate the time that comes by default from Go however this exposes us to two main issues:
1. As seen, changes between versions (of Go) can cause issues, for example you can not use time.Parse to parse this new time specification.
2. There is no standardized way for timestamps in REST Layer, which means that any changes (like pointed in the first issue) can cause the API more harm than good.

Thus, I suggest using UNIX timestamp as default for REST Layer.

**Comment by rs** [comment]
With UNIX timestamp we loose definition (second instead of nano) and ability to store dates before 1970. It would be also less efficient as most storers would have to convert them back to `time.Time` to reformat it.

**Comment by SAFAD** [comment]
SQL Based Storers already convert and parse the time.Time format to use it already (check the outdated SQLite 3 implementation) which raised this issue in the first place (the introduction of monotonic time in Go 1.9).

Now if we agree that it is OK to use the default time.Time format as is, we should consider the issue raised by Go 1.9 as it can not be parsed with time.Parse (See example here)[https://play.golang.org/p/R9oxdfeD5Ap] which seems to be a problem with Go itself.

Other than the default time.Time format should be taken into consideration.

**Comment by rs** [comment]
Regarding the pgsql module, it's awesome! Thanks fort the contrib. Feel free to send a PR to add its reference to the README.

Some feedback:
* There are some SQL injections opportunity:
  * [utils.go#L157](https://github.com/SAFAD/rest-layer-pgsql/blob/master/utils.go#L157)
  * [pgsql.go#L262](https://github.com/SAFAD/rest-layer-pgsql/blob/master/pgsql.go#L262) (Etag is opaque and not sanitized by REST layer IIRC).
  * [pgsql.go#L296](https://github.com/SAFAD/rest-layer-pgsql/blob/master/pgsql.go#L296)
  * [pgsql.go#L297](https://github.com/SAFAD/rest-layer-pgsql/blob/master/pgsql.go#L297)
* Using `LIKE` on equality (see [utils.go#L83](https://github.com/SAFAD/rest-layer-pgsql/blob/master/utils.go#L83)) is breaking the REST Layer API. Pattern matching should only be enabled when `$regex` is used.
* At [utils.go#L52](https://github.com/SAFAD/rest-layer-pgsql/blob/master/utils.go#L52), it would be more efficient to store substrings in a slice and use `strings.Join` (or to use a bytes.Buffer).
* Same remark for most of string concats in the rest of the function.
* Same remark in `valueToString` and `valuesToString`.
* At [pgsql.go#L58](https://github.com/SAFAD/rest-layer-pgsql/blob/master/pgsql.go#L58), `rowVals` and `rowValsPtr` could be reused for each lines to avoid allocation.
* At [pgsql.go#L279](https://github.com/SAFAD/rest-layer-pgsql/blob/master/pgsql.go#L279), do `a[:len(a)-1] = ")"` (same for next line) to avoid two allocations.

**Comment by rs** [comment]
Regarding time, as explained in the doc for `String`:

> The returned string is meant for debugging; for a stable serialized representation, use t.MarshalText, t.MarshalBinary, or t.Format with an explicit format string.

A JSON serialization would use `MarshalText` on the time. String on types in Go is most of the time not meant for serialization.

**Comment by smyrman** [comment]
> I don’t think REST layer should truncate the time. What if other storers want to use this to mesure timing for instance?

I thought about it, but storing the monotonic time? It's as far as I know process specific, is it not? I do agree we should not truncate any precision on the non-monothonic component. That said, I suppose if we use the correct `MarshalText` method, it should be a non-issue.

**Comment by SAFAD** [comment]
@rs Thank you for taking time to check our library, the current implementation is more of a Proof of Concept rather than a true implementation, it will be entirely overhauled later (as it is hard to read and maintain).

@rs @smyrman regarding the time issue, I will try and use `MarshalText` later and see the results, however for the current project we are working on it is a requirement to use UNIX timestamp for time, thus I will implement in my fork and use it for this project and continue maintaining the fork as the project needs and issue suggestions and PRs here for features we implement.

One final note: have anyone tested the library with MongoDB/ES/Google Datastore with Go 1.9 to see if there is an issue with the newly appended Monotonic time?

**Comment by rs** [comment]
@smyrman you're right, ok to truncate it then.

@SAFAD why do you need to fork to use UNIX time? I'm not sure to understand.

**Comment by smyrman** [comment]
> @rs @smyrman regarding the time issue, I will try and use MarshalText later and see the results, however for the current project we are working on it is a requirement to use UNIX timestamp for time, thus I will implement in my fork and use it for this project and continue maintaining the fork as the project needs and issue suggestions and PRs here for features we implement.

Rather than a fork, you could just implement your own FieldValidators and ready  Fields for your particular application.

**Comment by smyrman** [comment]
> One final note: have anyone tested the library with MongoDB/ES/Google Datastore with Go 1.9 to see if there is an issue with the newly appended Monotonic time?

@SAFAD, we have been using the MongoDB backend built with Go 1.8, 1.9 and 1.10 for a while without any issues related to Monotonic time. We are using the rest-layer `schema.UpdatedField` and `schema.CreatedField`.

btw, feel free to join us at `#rest-layer` on gophers.slack.com for any general questions you may have, not related to any particular issue.

**Comment by smyrman** [comment]
>At utils.go#L52, it would be more efficient to store substrings in a slice and use strings.Join (or to use a bytes.Buffer).

Not necessarily true :-P I think if you use a slice the data will probably escape to heap (rather than being generated in the stack), while for simple string arithmetic operations, most likely all the variables will be allocated on the stack, which means the memory will be automatically cleared when the function goes out of scope. In addition, if e.g. adding together mulitple strings on one line, the compiler may be smart about it.

Not worth pre-optimizing in other words. Make it work safely an correctly, and then benchmark to make it faster later on;-)

**Comment by apuigsech** [comment]
I had similar problems when writing the first POC of https://github.com/apuigsech/rest-layer-sql.

The reasons were incompatibilities on time formats between different parties that happens because I was building the full query on my own. You are also doing that on your driver.

Switching it to prepared statements allowed the SQL driver to handle it properly and the issue was fixed. In addition, it is best practices and safe to SQL injection attacks by design.

The Storer Handler I did should be valid for pgsql too, so I encourage you to try it.

**Comment by smyrman** [comment]
I am going to close this issue; one is supposed to use the Time's Format method, and not it's Stringer interface for getting a value that's not for debugging purposes.

Still,  PR #219 is slightly related, as it will remove the monotonic time component when validating times.
