### ISSUE TITLE
Validate fields depending on other field values

### ISSUE THREAD

**Issue by AlexCppns** [rs/rest-layer#251]
Is there a way to build a custom validator that looks at 2 different fields?

**Comment by smyrman** [comment]
Maybe sort-of through the `Dependency` property... Otherwise it's possible to use an `schema.AnyOf` validator to wrap two schemas, but that is not yet available as a top-level schema.

rest-layer dependency allows describing a _query_ that the full object must match for a field to be allowed. For reference, [JSON-schema dependencies](https://json-schema.org/understanding-json-schema/reference/object.html#dependencies) does something similar, but uses a _schema_ (not a query).

If you describe your use-case I can give a better answer.

**Comment by smyrman** [comment]
Will close this issue.
